### PR TITLE
[Patch]Fix time and location display bug

### PR DESCRIPTION
**Pull request by stvreumi**

### CODE REVIEW

**Comment by icecat2012** [comment]
@Billy4195 Can this patch merge to master directly? Or we quickly test recently commits and make it as a version.

**Comment by stvreumi** [comment]
I separate this branch from dev, so if it merges to master, it will merge some commits after last version.
Should I separate new branch from master and create new PR?

**Comment by icecat2012** [comment]
Wait for his answer to decide what to do.

**Comment by Billy4195** [comment]
I think we can merge into master ASAP, in order to fix the bug.

**Pull request merged**
