### PR TITLE
modify check_user_existed_or_signup

### PR DESCRIPTION
**Pull request by stvreumi**
I am not sure about `createNewUser` correctness. Please help me check. Thanks.
And I also want to ask why the variable `ret` is needed.(in line 448 of the original `server_api.py`)

### CODE REVIEW

**Comment by Billy4195** [comment]
@stvreumi One PR for one purpose to change.

**Comment by chenyang14** [comment]
`createNewUser` runs failed,because of using string format in `VALUES` .
[](https://stackoverflow.com/questions/36797680/pymysql-how-to-format-types-on-query) See this for more detail.

**Comment by stvreumi** [comment]
@chenyang14 I also check the documentation. It seems that only this expression is available when using `cursor.execute()`. I finally pass SQL string and data tuple to this function.
documentation: 
https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursor-execute.html

**Comment by stvreumi** [comment]
@Billy4195 I have a problem when separating this PR. If I only move one SQL string to `dataAccessObjects.py`, I can't delete redundant function such as `db.connect()`.
Should I change only one place and waiting for the merge, then do another change?
Or should I add two commits on this branch?

**Comment by Billy4195** [comment]
@stvreumi I think the `db.connect` can be deleted in later PR.
The less complicate change in a PR will be easier for us to review the code.

**Comment by stvreumi** [comment]
@Billy4195 OK. I think I would keep this PR and open another two PR to do the modification.
When I finish modification, I will close this PR.

**Comment by stvreumi** [comment]
Since I have applied all the changes in this commit, I will close this PR.

**Pull request closed without merging**
