### PR TITLE
Add location and description in event

### PR DESCRIPTION
**Pull request by stvreumi**

### CODE REVIEW

**Comment by stvreumi** [comment]
I'm not sure if I have to change css file

**Comment by Billy4195** [comment]
@stvreumi Change CSS for ?

**Comment by stvreumi** [comment]
I'm not sure if there is some style should be applied on the location.
BTW there's some bug on the schedule crawling. I can't show all the schedule in the calendar when I run the board.
I will fix it ASAP.

**Comment by Billy4195** [comment]
You can open an issue to describe the bug, and how to duplicate it.

**Comment by stvreumi** [comment]
@Billy4195 I have fixed it, should I need to open an issue about that bug?

**Comment by Billy4195** [comment]
No, you just create a new PR and describe the problem on it.

**Comment by stvreumi** [comment]
I add time attribute if the event is not all day.

**Pull request merged**
