### PR TITLE
Add auto news text generator

### PR DESCRIPTION
**Pull request by icecat2012**

### CODE REVIEW

**Comment by Billy4195** [comment]
Please use pip to install package, do not add other package's source code.

**Comment by icecat2012** [comment]
I had tried to install tinyurl3 by pip3.
However, pip3 install's version got a bug-- None of url can be shorten.
After tracing the code, I found out pip3 version got a addition space which cause the bug.
That's why I decided to clone the github source code.
image

**Comment by Billy4195** [comment]
Or had you tried to install using source code?
The reason that I don't want our project contain other packages' source code is that the packages is not the essential part that we must have and it may be `difficult` to update or upgrade these packages that we using its source code.

**Comment by icecat2012** [comment]
I am not sure what `Or had you tried to install using source code?` means?
You mean clone down then run it's set up?

**Comment by Billy4195** [comment]
Yes, if this method can install the package, then it doesn't need to contain the source code, but you should add the installation steps in the README.md

**Comment by icecat2012** [comment]
@Billy4195 
No more using tinyurl3 lib, but connect to tinyurl api by ourselves

**Comment by Billy4195** [comment]
Please solve the conflict.

**Comment by icecat2012** [comment]
Done

**Comment by Billy4195** [comment]
If we add the forum name(ex: Techorange, medium, Inside) near the article's title, it will be clear for user to know where are these article from.
If I am a new user didn't know where these QR will direct to, would not scan the QR code to see what will happened, because the website may be the Phishing website.

**Comment by icecat2012** [comment]
@mickey8820062008 
As @Billy4195 said, it will be better to add the forum name.
I will add `forum_name1 ` and `forum_name2` in json data.
Please design some boxes to show them.

**Pull request merged**
