### PR TITLE
[Patch]Add self parameter in generateNewId(TextDao)

### PR DESCRIPTION
**Pull request by stvreumi**

### CODE REVIEW

**Comment by Billy4195** [comment]
@icecat2012 @chenyang14 I think this will cause error, please review ASAP.

**Comment by icecat2012** [comment]
@Billy4195  What kind of error?
@stvreumi  Did you try it before push?

This is a simple test on python online editor. It seems no problem.
image

**Comment by Billy4195** [comment]
@icecat2012 because the `generateNewId()` is a class method
In default, class will pass a self reference into its class method, but the `generateNewId()` accept no parameter now, then will cause the error.

**Comment by icecat2012** [comment]
I didn't get it....
Parent class seems can use child class variable.

image

**Comment by Billy4195** [comment]
No, you need to delete the self parameter in class B a(), then it will be same condition in this PR.

**Comment by stvreumi** [comment]
I just saw that parameter is missing, so I make a PR to modify it.
The test seems nothing wrong when I first added `generateNewId`.

**Comment by chenyang14** [comment]
With 'self' as parameter inside,it would be correct

**Comment by icecat2012** [comment]
I thought this commit is adding `self` to fix the problem.
That's why I add self in B().a(). 
image

**Pull request merged**
