### PR TITLE
Add generateNewId in DataManipulateDao and TextDao

### PR DESCRIPTION
**Pull request by stvreumi**

### CODE REVIEW

**Comment by stvreumi** [comment]
OK, finish modification

**Comment by Billy4195** [comment]
oh, sorry... 
The variable name should follow lower camel case, so `Id` needs change to `id`

**Comment by stvreumi** [comment]
Is `id` a reserved word in Python?

**Comment by Billy4195** [comment]
oh... yes, it it the built in function.
OK, just use `Id` .

**Pull request merged**
